### PR TITLE
VS builds, I/O & fixes

### LINKED ISSUE #62: Problem with XWAV playback affecting some files
> Dear Sir,
> just a notice from one of the humble admirers of your foobar2000
> vgmstream coding works.
> Alas, since the beginning of 2017 the updates of 
> foo_input_vgmstream.fb2k-component.zip as well as of 
> vgmstream...-test-u.zip (in cooperation with bnnm I think whose email 
> address I can't come upon so I'm left with pestering you) contain 
> in_vgmstream.dll / xmp-vgmstream.dll / foo_input_vgmstream.dll files 
> that render at least my xwav files (maybe others too) stuttering to 
> unhearable.
> I was lucky enough to get older well working versions from 2016, that is 
> in_vgmstream.dll, r1050-166-g1899a20, 2016-12-27, and xmp-vgmstream.dll, 
> r1050-92-g577df6d, 2016-11-26, but wasn't able to find a corresponding 
> older version of foo_input_vgmstream.dll on the net. My OS is still 
> Windows XP.
> Since I haven't got the slightest notion of coding myself, I hope not to 
> be too brash and not to disturb your workflow too much asking you to 
> have an occasional look at that phenomenon.
> Please excuse my quirky English, my mother language is German. Thank you 
> very much in advance.

[Attachment 2017-01-15.zip](https://github.com/kode54/vgmstream/files/706419/Attachment.2017-01-15.zip)

### PR DESCRIPTION
**Pull request by bnnm**
- Added SCD DSP Wii U [Dragon Quest X (Wii U)]
- Fixed regression in Xbox codecs
- Big speedup in test.exe, and Winamp/foobar seeking in some cases
- (dev) I/O optimizations
- (dev) easier Visual Studio builds for foobar/test/winamp

Closes #62

I/O notes:
I did some ghetto profiling and 99% of the time was spent doing I/O, especially when buggy metas request data over filesize. So I increased the I/O buffers, did some streamfile optimizations and tested decently; keep an eye just in case.
There is room for improvements since some layouts jump around trashing the buffers.

VS notes:
Compiling all modules with VS should be easy enough now (with a couple of extra steps detailed in BUILD.md). I think I'll add xmplay to vgmstream_full.sln later and kill xmp-vgmstream.sln, unless you want it around.

### CODE REVIEW

File: fb2k/in_vgmstream.cpp [hunk 1]
```diff
@@ -250,6 +252,11 @@ void input_vgmstream::decode_seek(double p_seconds,abort_callback & p_abort) {
 	int max_buffer_samples = sizeof(sample_buffer)/sizeof(sample_buffer[0])/vgmstream->channels;
 	bool loop_okay = loop_forever && vgmstream->loop_flag && !ignore_loop && !force_ignore_loop;
 
+	/* start on first channel to avoid problems in some decoders */
```
Comment (kode54) [inline fb2k/in_vgmstream.cpp]: What is the meaning of this? This sample count is in whole frames, not N samples per channel.

Comment (bnnm) [inline fb2k/in_vgmstream.cpp]: I was under the impression seek_pos_samples=0 would mean first sample in first channel, seek_pos_samples=1 first sample in second channel, and so on.
I guess I misunderstand the issue. Here is one easy test from [FF XI](https://github.com/kode54/vgmstream/files/706992/music076.zip). Seek and half of the time you'll get garbled sounds (hence I thought it was landing on a sample of an odd channel).

This happened before any of my IO changes.
